name: Nix Builder

on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-substituters = https://spotnix.cachix.org
          extra-trusted-public-keys = spotnix.cachix.org-1:nZRREPI6Zw9oqfuKctrDuIdoYw7R2vSy47tX0OgjgkY=
    - uses: cachix/cachix-action@v10
      with:
        name: spotnix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix build
